#!/usr/bin/env bash

if [[ $# -le 1 ]] ; then echo "Please, provide the remote host name" ; exit 1 ; fi

# add public key to authorized_keys
cat ~/.ssh/id_rsa.pub | ssh $1 'mkdir -p .ssh && cat - >>.ssh/authorized_keys'
